[package]
name = "foq"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
argon2 = "0.5.2"
async-trait = "0.1.73"
chrono = "0.4.31"
config = { version = "0.13.3", features = ["toml"] }
derive_builder = "0.12.0"
dyn-clone = "1.0.13"
once_cell = "1.18.0"
rustls = { version = "0.21.7", features = ["quic", "dangerous_configuration"] }
rustls-pemfile = "1.0.2"
s2n-quic = { version = "~1.28.0", default-features = false, features = ["provider-address-token-default", "provider-tls-rustls", "provider-event-tracing"] }
sqlx = { version = "0.7.1", default-features = false, features = ["runtime-tokio-rustls", "sqlite", "macros", "migrate"] }
strum = "0.25.0"
strum_macros = "0.25.2"
thiserror = "1.0.48"
tokio = { version = "1.27.0", features = ["full"] }
tokio-rustls = { version = "0.24.1", features = ["dangerous_configuration"] }
tokio-util = "0.7.8"
tracing = "0.1.37"
tracing-attributes = "0.1.26"
tracing-subscriber = "0.3.17"
unicode-segmentation = "1.10.1"
regex = "1.9.5"
zeroize = { version = "1.6.0", features = ["derive"] }

[dev-dependencies]
blake3 = "1.4.1"
uuid = { version = "1.4.1", features = ["v4"] }
quinn = "0.10.2"
