[package]
name = "foq"
version = "0.5.1"
authors = ["Valentín Bolfík"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
argon2 = "0.5.3"
async-channel = "2.3.1"
async-trait = "0.1.81"
aws-lc-rs = { version = "1.8.0", features = ["bindgen"]}
chrono = "0.4.38"
config = { version = "0.14.0", features = ["toml"] }
derive_builder = "0.20.0"
dyn-clone = "1.0.17"
futures = "0.3.30"
once_cell = "1.19.0"
path-clean = "1.0.1"
regex = "1.10.5"
rustls = { version = "0.23.11"}
rustls-pemfile = "2.1.2"
s2n-quic = { version = "1.42.0", default-features = true, features = ["provider-tls-rustls", "provider-event-tracing", "zeroize"] }
sqlx = { version = "0.7.4", default-features = false, features = ["runtime-tokio", "sqlite", "macros", "migrate"] }
strum = "0.26.3"
strum_macros = "0.26.4"
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
tokio-rustls = { version = "0.26.0" }
tokio-util = "0.7.11"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-attributes = "0.1.27"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
unicode-segmentation = "1.11.0"
zeroize = { version = "1.8.1", features = ["derive"] }

[dev-dependencies]
blake3 = "1.5.1"
quinn = "0.11.2"
uuid = { version = "1.10.0", features = ["v4"] }
