[package]
name = "foq"
version = "0.7.2"
authors = ["Valentín Bolfík"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.98"
argon2 = "0.5.3"
async-channel = "2.3.1"
async-trait = "0.1.88"
chrono = "0.4.41"
config = { version = "0.15.11", features = ["toml"] }
derive_builder = "0.20.2"
dyn-clone = "1.0.19"
futures = "0.3.31"
once_cell = "1.21.3"
path-clean = "1.0.1"
quinn =  "0.11.7"
regex = "1.11.1"
rustls = { version = "0.23.26", default-features = false, features = ["aws_lc_rs"]}
rustls-pemfile = "2.2.0"
s2n-quic = { version = "1.57.0", default-features = true, features = ["provider-tls-rustls", "provider-event-tracing", "zeroize"] }
sqlx = { version = "0.8.5", default-features = false, features = ["runtime-tokio", "sqlite", "macros", "migrate"] }
strum = "0.27.1"
strum_macros = "0.27.1"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["full", "tracing"] }
tokio-rustls = "0.26.2"
tokio-util = "0.7.15"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-attributes = "0.1.28"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
unicode-segmentation = "1.12.0"
walkdir = "2.5.0"
zeroize = { version = "1.8.1", features = ["derive"] }

[dev-dependencies]
blake3 = "1.8.2"
uuid = { version = "1.16.0", features = ["v4"] }

[profile.dev.package.sqlx-macros]
opt-level = 3

[target.'aarch64-linux-android'.dependencies]
aws-lc-rs = { version = "1.13.0", features = ["bindgen"]}
