[package]
name = "foq"
version = "0.6.1"
authors = ["Valentín Bolfík"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
argon2 = "0.5.3"
async-channel = "2.3.1"
async-trait = "0.1.83"
aws-lc-rs = { version = "1.10.0"}
chrono = "0.4.38"
config = { version = "0.14.0", features = ["toml"] }
derive_builder = "0.20.1"
dyn-clone = "1.0.17"
futures = "0.3.31"
once_cell = "1.20.1"
path-clean = "1.0.1"
quinn = "0.11.5"
regex = "1.11.0"
rustls = { version = "0.23.14"}
rustls-pemfile = "2.2.0"
s2n-quic = { version = "1.47.0", default-features = true, features = ["provider-tls-rustls", "provider-event-tracing", "zeroize"] }
sqlx = { version = "0.8.2", default-features = false, features = ["runtime-tokio", "sqlite", "macros", "migrate"] }
strum = "0.26.3"
strum_macros = "0.26.4"
thiserror = "1.0.64"
tokio = { version = "1.40.0", features = ["full", "tracing"] }
tokio-rustls = { version = "0.26.0" }
tokio-util = "0.7.12"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-attributes = "0.1.27"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
unicode-segmentation = "1.12.0"
walkdir = "2.5.0"
zeroize = { version = "1.8.1", features = ["derive"] }

[dev-dependencies]
blake3 = "1.5.4"
uuid = { version = "1.10.0", features = ["v4"] }

[profile.dev.package.sqlx-macros]
opt-level = 3

[target.'aarch64-linux-android'.dependencies]
aws-lc-rs = { version = "1.10.0", features = ["bindgen"]}
