[package]
name = "foq"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
argon2 = "0.5.2"
async-trait = "0.1.74"
chrono = "0.4.31"
config = { version = "0.13.3", features = ["toml"] }
derive_builder = "0.12.0"
dyn-clone = "1.0.16"
once_cell = "1.18.0"
rustls = { version = "0.21.9", features = ["quic", "dangerous_configuration"] }
rustls-pemfile = "1.0.4"
s2n-quic = { version = "1.31.0", default-features = true, features = ["provider-tls-rustls", "provider-event-tracing"] }
sqlx = { version = "0.7.2", default-features = false, features = ["runtime-tokio-rustls", "sqlite", "macros", "migrate"] }
strum = "0.25.0"
strum_macros = "0.25.3"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["full"] }
tokio-rustls = { version = "0.24.1", features = ["dangerous_configuration"] }
tokio-util = "0.7.10"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-attributes = "0.1.27"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
unicode-segmentation = "1.10.1"
regex = "1.10.2"
zeroize = { version = "1.7.0", features = ["derive"] }
path-clean = "1.0.1"
futures = "0.3.29"

[dev-dependencies]
blake3 = "1.5.0"
uuid = { version = "1.5.0", features = ["v4"] }
quinn = "0.10.2"

[profile.dev.package.sqlx-macros]
opt-level = 3
