[package]
name = "foq"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
argon2 = "0.5.0"
async-trait = "0.1.68"
chrono = "0.4.24"
derive_builder = "0.12.0"
dotenvy = "0.15.6"
dyn-clone = "1.0.11"
once_cell = "1.17.1"
rustls = { version = "0.21.0", features = ["quic", "dangerous_configuration"] }
rustls-pemfile = "1.0.2"
s2n-quic = { version = "1.18.0", default-features = false, features = ["provider-address-token-default", "provider-tls-rustls"] }
sqlx = { version = "0.6.3", features = ["runtime-tokio-rustls", "sqlite", "sqlx-macros"] }
strum = "0.24.1"
strum_macros = "0.24.3"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["full"] }
tokio-util = "0.7.8"
tracing = "0.1.37"
tracing-attributes = "0.1.24"
tracing-subscriber = "0.3.17"
unicode-segmentation = "1.10.1"

[dev-dependencies]
blake3 = "1.3.3"
uuid = { version = "1.3.1", features = ["v4"] }
