DATABASE_URL = "sqlite://foq-dev.sqlite"
certificate_file = "certs/test-cert.pem"
key_file = "certs/test-key.pem"
ca_chain_file = "certs/test-ca-chain.pem"
tcp_address = "0.0.0.0:2121"
tcp_tls_address = "0.0.0.0:991"
quic_address = "0.0.0.0:9991"
quinn_address = "0.0.0.0:22222"
log_level = "debug"
logfile = "foq-dev.log"
log_filter = "foq=DEBUG"