DATABASE_URL = "sqlite://foq-dev.sqlite"
certificate_file = "certs/test-cert.pem"
key_file = "certs/test-key.pem"
ca_chain_file = "certs/test-ca-chain.pem"
tcp_address = "0.0.0.0:21"
tcp_tls_address = "0.0.0.0:990"
quic_address = "0.0.0.0:9990"
log_level = "debug"
logfile = "foq.log"