DATABASE_URL = "sqlite://foq-dev.sqlite"
certificate_file = "certs/cert.pem"
key_file = "certs/key.pem"
ca_chain_file = "certs/ca-chain.pem"
tcp_address = "0.0.0.0:21"
tcp_tls_address = "0.0.0.0:990"
quic_address = "0.0.0.0:9990"
log_level = "debug"